name: pusher_beams
description: Official Flutter Plugin for Pusher Beams, receive notifications easily on your Flutter application with Pusher Beams.
version: 1.1.2
repository: https://github.com/pusher/push-notifications-flutter
issue_tracker: https://github.com/pusher/push-notifications-flutter/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  pusher_beams_platform_interface: ^1.1.1
  pusher_beams_android: ^1.1.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.16
  
flutter:
  plugin:
    platforms:
      android:
        default_package: pusher_beams_android
    






